name: Sync Fork

on:
  schedule:
    - cron: '0 2 * * *' # every day at 2h00
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream repo
        run: |
          git remote add upstream https://github.com/iterativv/NostalgiaForInfinity.git
          git fetch upstream --tags

      - name: Merge upstream main
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories

      - name: Push changes to fork
        run: |
          # If there are no changes, this will do nothing
          git push origin main --tags
